### ISSUE TITLE
evalAdmix  SIGSEGV, Segmentation fault

### ISSUE THREAD

**Issue by einararn** [GenisGE/evalAdmix#2]
Hi,
I get a SIGSEGV, Segmentation fault running evalAdmix on my data. I am on a fedora 31 and also on CentOS 8.0 with the same issue.

No problem running the test data on http://www.popgen.dk/software/index.php/EvalAdmix

But my own (rather largish) data set estimated using admixture give me the following:

evalAdmix version 0.95
evalAdmix -plink prelim.filtered.Chromosomes -fname prelim.filtered.Chromosomes.8.P -qname prelim.filtered.Chromosomes.8.Q -P 8 
        -> Will assume these are the plink files:
                bed: prelim.filtered.Chromosomes.bed
                bim: prelim.filtered.Chromosomes.bim
                fam: prelim.filtered.Chromosomes.fam
Warning the plink file appears to have non autosomal chromosomes (chromosome number > 22) and/or undefined chromosomes (chromosome name=0)
        -> Plink file contains 11629571 autosomale SNPs
        -> reading genotypes Segmentation fault (core dumped)

gdb -q evalAdmix -c /var/crash/core.evalAdmix.204564.smyrill.1629750211
Reading symbols from evalAdmix...
(No debugging symbols found in evalAdmix)
[New LWP 204564]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `evalAdmix -plink prelim.filtered.Chromosomes -fname prelim.filter'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __memset_avx2_erms () at ../sysdeps/x86_64/multiarch/memset-vec-unaligned-erms.S:151
151             rep stosb

Is this a bug in evalAdmix or is there a size limit?

Thanks
Einar

**Comment by stevemussmann** [comment]
Hello, I am experiencing the same issue with version 0.95, although my file size is much smaller (8,078 SNPs). I can run the same files through version 0.9 without experiencing this issue.

**Comment by stevemussmann** [comment]
The issue seems to be coming from the char buffer sizes in Cinterface.cpp. I reset all to 100000 and the segmentation faults went away.

`int lens=100000;
char buff[lens];`

**Comment by einararn** [comment]
I tried version 0.9 and I still get the same problem.

**Comment by einararn** [comment]
If I reduce the number of individuals and the number of sites everything is fine:

K=6   nSites=955368   nInd=495 works with both 0.90 and 0.95

**Comment by GenisGE** [comment]
Hi Einar and Steve,

In principle there should not be a size limit, so it is a bug. Thanks Steve for pointing to the buffer size, I have reset it too in the github version. I edited it recently during debugging with another user and forgot to set it back, sorry about that.

How large was your initial dataset Einar? I have run it successfully with ~15 million sites but only a bit more than 100 individuals, will try to see if I can make it work with larger datasets.

Best,
Genis

**Comment by einararn** [comment]
Hi Genis,

When I run 495 individuals and 955368 SNPs everything is OK

When I run 495 individuals and 8923277 SNPs I get Segmentation fault

When I run 1199 individuals and 11629571 SNPs I get Segmentation fault

This is what I've tried

Best regards
Einar

-----------------------------------------------------
Einar Arnason, Professor  Emeritus   ***@***.***
Institute of Biology
University of Iceland
Askja # 245                 office   354-525-4613
Sturlugata 7
101 Reykjavik
Iceland
-----------------------------------------------------

**Comment by Rebbeca1985** [comment]
Hi Genis and einararn,
    I met the similar problem, even with the updated Cinterface.cpp.
   My data has 2671914 SNP sites and 2448 samples.
  When I run this data, I get the following log:
        -> Will assume these are the plink files:
                bed: core_ld0.5.bed
                bim: core_ld0.5.bim
                fam: core_ld0.5.fam
        -> Plink file contains 2671914 autosomale SNPs
        -> reading genotypes    -> Tried to allocate: 26.313 gig memory
        -> Allocation failed, likely cause: need more memory, will exit.
The memory of HPC  is enough. The node has 64 cpus and 252Gb mems.

I tried to change the int lens parameter in Cinterface.cpp, but it doesn't work.  
Is this a bug in evalAdmix or is there a size limit?

**Comment by GenisGE** [comment]
Dear Einar and Rebbeca,

I have updated evalAdmix so it can allocate larger datasets, so in principle now the limiting factor should be the available memory in you system instead of the evalAdmix allocation. I have also made the memory handling more efficient. That should hopefully solve the issue, sorry Einar for the long delay in dealing with it.

One potential problem that persists is that when running in parallel, evalAdmix needs to temporary store in memory an NxM and an MxK  matrices for each thread used, which leads to a big use of memory that can easily fill the memory (in the server I am testing with 376 Gb of memory I cannot run a dataset with 711 samples and 7337603 sites with 20 threads, but I can run it with 10 threads). This is not so easy to solve given the current evalAdmix algorithm, the way around is either running with less threads or using the --useSites option to subsample the data before running, since evalAdmix usually does not need that many sites anyways.

Best,
Genis

**Comment by zjnolen** [comment]
Hi all,

I am not sure if this is a related issue, but I have been getting segmentation faults with even relatively small datasets (60 samples, ~70000 sites), always occurring immediately after finishing the steps `Estimating freqs without ind ##`. I've found this happens on both 0.95 and 0.96, so it may be unrelated to this issue (I haven't yet been able to test on another system, the closest I've come is testing within and outside a singularity container).

The run of evalAdmix looks like this:
```
evalAdmix version 0.96
evalAdmix -beagle results/pargus/beagle/test.beagle.gz -fname results/pargus/ngsadmix/test_K3.fopt.gz -qname results/pargus/ngsadmix/test_K3.qopt -o test.corres 
Going to read beagle file
Input file has dim: nsites=77034 nind=61
                ->K=3   nSites=77034    nInd=61
opening : results/pargus/ngsadmix/test_K3.qopt with x=61 y=3
opening : results/pargus/ngsadmix/test_K3.fopt.gz with x=77034 y=3
Finished calculating normal residuals
[1]    29836 segmentation fault (core dumped) evalAdmix -beagle  -fname  -qname  -o 
```

With the coredump looking like this:
```
gdb -q evalAdmix -c core.29836                            
Reading symbols from evalAdmix...(no debugging symbols found)...done.
BFD: Warning: core.29836 is truncated: expected core file size >= 207376384, found: 12288.
[New LWP 29836]
Failed to read a valid object file image from memory.
Core was generated by `evalAdmix -beagle results/pargus/'.
Program terminated with signal 11, Segmentation fault.
#0  0x0000000000412083 in ngsevalAdmix(double*, int, int, double**, double*, double**, int, double**, double**, int, int, int, char**, int) ()
```
The core dump seems to be missing the whole command when it says `Core was generated by`, but I am rather new at looking at core dumps, so can't say if that is normal or not. Visually inspecting the input files, all seem to be complete and as expected, and this happens on multiple independently created beagle files for my dataset. Would any of you have suggestions given the fault information I get?

Thanks!
Zach

**Comment by GenisGE** [comment]
Hi Zach,

thanks for reporting this issue, it was due to a bug in the code in the non multi threaded version of the program with beagle input. It didn't affect the multi threaded version, i guess that's why it went unnoticed for so long. I think it is fixed now, let me know if you still meet the error.

Thanks for reporting it, it was a very small bug but with big consequences since it didn't allow to run.

It was a totally different issue than the initial one here though, but that's fine :)

Cheers,
Genis

**Comment by GenisGE** [comment]
I am closing this issue since I think is is solved. Please let me know if anyone encounters similar problems.

Genis
