### ISSUE TITLE
Question about estimating ancestry admixture

### ISSUE THREAD

**Issue by Pharmacogenetecist** [GenisGE/evalAdmix#4]
Is it possible to assign admixed ancestry based on a reference population?
I generated Plink files from 70 individual WES of unknown ethnicity.
I have generated  .P and .Q files using admixture using Admixture.
How would I estimate ancestry per sample?

![Rplot_evalAdmix](https://github.com/GenisGE/evalAdmix/assets/82195229/c5e632d1-34df-431e-ad1a-1c6ad67ecb0b)

**Comment by GenisGE** [comment]
Hi, 

I am afraid this question is in the wrong repo, evalAdmix does not estimate admixture proportions, it just takes them as input and estimates the correlation of residuals as an evaluation of the model fit.

But I can anyways answer your question, yes you can assign ancestry based on reference populations using ADMIXTURE in supervised mode, see section 2.10 of the admixture manual:

https://vcru.wisc.edu/simonlab/bioinformatics/programs/admixture/admixture-manual.pdf

Hope it helps,
Genis

**Comment by Pharmacogenetecist** [comment]
Thank you, appreciate your message.
